apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: falco-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: cel-trig-with-matches
      interceptors:
        - cel:
            filter: >-
              header.match('Falcon', 'true')
      bindings:
        - ref: falco-binding
      template:
        ref: falco-trigger-template
