apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-run-
  namespace: falcoresponse
spec:
  pipelineRef:
    name: hello
  params:
    - name: body
      value: "somuchoutput"
