apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello
  namespace: falcoresponse
spec:
  params:
    - name: body
      description: The entire msg from falco
      default: myBody
    - name: output
      description: The output from falco
      default: myOutput
    - name: priority
      description: The priority from falco
      default: myPriority
    - name: rule
      description: The triggerd falco rule
      default: myRule
  tasks:
    - name: run-hello
      taskRef:
        name: hello
      params:
        - name: body
          value: "$(params.body)"
        - name: output
          value: "$(params.output)"
        - name: priority
          value: "$(params.priority)"
        - name: rule
          value: "$(params.rule)"
