apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello
  namespace: falcoresponse
spec:
  params:
    - name: output
      description: The output from falco
    - name: priority
      description: The priority from falco
    - name: rule
      description: The triggerd falco rule
  tasks:
    - name: run-hello
      taskRef:
        name: hello
      params:
        - name: output
          value: "$(params.output)"
        - name: priority
          value: "$(params.priority)"
        - name: rule
          value: "$(params.rule)"
