apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
  namespace: falcoresponse
spec:
  params:
    - name: body
      description: The entire msg from falco
  steps:
    - name: hello
      image: ubuntu
      command:
        - echo
      args:
        - "$(params.body)"
