---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pod-delete
  namespace: falcoresponse
spec:
  params:
    - name: falco-event
      description: The entire msg from falco
  steps:
    - name: pod-delete
      image: quay.io/nissessenap/poddeleter@sha256:323524ac50274a51f5dfdb70bf3ea0d24c57b0ca312b5fbcaa9c81446d5da998
      env:
        - name: BODY
          value: $(params.falco-event)
