apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: falco-binding
spec:
  params:
    - name: output
      value: $(body.output)
    - name: priority
      value: $(body.priority)
    - name: rule
      value: $(body.rule)
