apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: falco-binding
  namespace: falcoresponse
spec:
  params:
    - name: body
      value: $(body)
    #- name: output
    #  value: $(body.output)
    #- name: priority
    #  value: $(body.priority)
    #- name: rule
    #  value: $(body.rule)
