apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: falco-trigger-template
  namespace: falcoresponse
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
    - name: body
      description: The entire msg from falco
    #- name: output
    #  description: The output from falco
    #- name: priority
    #  description: The priority from falco
    #- name: rule
    #  description: The triggerd falco rule
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: hello-pipeline-run-
      spec:
        pipelineRef:
          name: hello
        params:
          - name: body
            value: $(tt.params.body)
          #- name: output
          #  value: $(tt.params.output)
          #- name: priority
          #  value: $(tt.params.priority)
          #- name: rule
          #  value: $(tt.params.rule)
